# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - your-username

patreon: # Replace with a single Patreon username
  - your-username

open_collective: # Replace with a single Open Collective username
  - your-username

ko_fi: # Replace with a single Ko-fi username
  - your-username

tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
  - your-username

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
  - your-username

liberapay: # Replace with a single Liberapay username
  - your-username

issuehunt: # Replace with a single IssueHunt username
  - your-username

otechie: # Replace with a single Otechie username
  - your-username

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://www.paypal.com/donate?hosted_button_id=XXXXX
  - https://www.buymeacoffee.com/your-username
